### ISSUE TITLE
Trying to query patientsList returns 400

### ISSUE THREAD

**Issue by IAmVolvic** [uldahlalex/react-assignment#1]
When passing a query table to the provided function -> `apiClient.patients.patientsList({name: 'bob'}).then((res) => res.data)`

Will return a 400 error:
```
{
  "code": "PGRST100",
  "details": "unexpected \"'\" expecting \"not\" or operator (eq, gt, ...)",
  "hint": null,
  "message": "\"failed to parse filter ('bob')\" (line 1, column 1)"
}
```

I cannot seem to solve this issue

**Comment by IAmVolvic** [comment]
nvm, I needed to use additional formatting / escaping for it to work

**Comment by uldahlalex** [comment]
Yeah, in this case postREST wants you to use "eq." operator and then the value since it can perform many different query operations based on the property value. Also see: https://docs.postgrest.org/en/v12/references/api/tables_views.html
